"""update_schema

Revision ID: 817c2dd00572
Revises: None
Create Date: 2026-04-08 18:04:46.423038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '817c2dd00572'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Data cleanup: Remove orphaned campaigns that would block the 'NOT NULL' constraint
    op.execute("DELETE FROM campaigns WHERE user_id IS NULL")
    
    op.alter_column('campaigns', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_communication_logs_campaign_id'), 'communication_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_direction'), 'communication_logs', ['direction'], unique=False)
    op.create_index(op.f('ix_communication_logs_dm_id'), 'communication_logs', ['dm_id'], unique=False)
    op.create_index(op.f('ix_decision_makers_campaign_id'), 'decision_makers', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_decision_makers_status'), 'decision_makers', ['status'], unique=False)
    op.create_index(op.f('ix_decision_makers_target_company_id'), 'decision_makers', ['target_company_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_campaign_id'), 'email_drafts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_decision_maker_id'), 'email_drafts', ['decision_maker_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_status'), 'email_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_target_companies_campaign_id'), 'target_companies', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_target_companies_status'), 'target_companies', ['status'], unique=False)
    # Robust handling of Enum type: Drop stale type if it exists from previous failed attempts
    op.execute("DROP TYPE IF EXISTS userrole CASCADE")
    
    # Create Enum type before using it in alter_column (using lowercase values to match UserRole enum)
    userrole_enum = sa.Enum('super_admin', 'admin', 'user', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=False)

    # Step 1: Drop existing default that blocks the type cast
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")

    # Step 2: Alter the column type with explicit cast and lowercase transformation
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=userrole_enum,
               postgresql_using="LOWER(role)::userrole")
    
    # Step 3: Re-apply the default with the new type
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user'::userrole")
    op.alter_column('users', 'demo_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_created_by_id'), 'users', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_constraint(op.f('users_created_by_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_created_by_id_fkey'), 'users', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_id'), table_name='users')
    op.alter_column('users', 'demo_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_index(op.f('ix_user_company_intel_campaign_id'), table_name='user_company_intel')
    op.drop_index(op.f('ix_target_companies_status'), table_name='target_companies')
    op.drop_index(op.f('ix_target_companies_campaign_id'), table_name='target_companies')
    op.drop_index(op.f('ix_email_drafts_status'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_decision_maker_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_campaign_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_decision_makers_target_company_id'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_status'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_campaign_id'), table_name='decision_makers')
    op.drop_index(op.f('ix_communication_logs_dm_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_direction'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_campaign_id'), table_name='communication_logs')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.alter_column('campaigns', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
