"""update_schema

Revision ID: c12eadd4803e
Revises: 817c2dd00572
Create Date: 2026-04-08 18:14:35.347393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12eadd4803e'
down_revision: Union[str, None] = '817c2dd00572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_company_intel_campaign_id'), 'user_company_intel', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_company_intel_campaign_id'), table_name='user_company_intel')
    # ### end Alembic commands ###
