"""add_google_token_columns

Revision ID: c740bed4034c
Revises: a20260521_0009
Create Date: 2026-05-21 19:58:43.056356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c740bed4034c'
down_revision: Union[str, None] = 'a20260521_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('oauth_accounts', sa.Column('token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_accounts', 'token_expiry')
    op.drop_column('oauth_accounts', 'access_token')
    # ### end Alembic commands ###
