"""add_v2_intel_columns

Revision ID: e4084b1ac1e1
Revises: f0a98272d0a6
Create Date: 2026-05-12 11:01:34.869803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4084b1ac1e1'
down_revision: Union[str, None] = 'f0a98272d0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_companies', sa.Column('v2_intel', sa.JSON(), nullable=True))
    op.add_column('user_company_intel', sa.Column('v2_intel', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_company_intel', 'v2_intel')
    op.drop_column('target_companies', 'v2_intel')
    # ### end Alembic commands ###
