"""update_schema

Revision ID: e9853fd6055d
Revises: c12eadd4803e
Create Date: 2026-04-09 13:16:32.016894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9853fd6055d'
down_revision: Union[str, None] = 'c12eadd4803e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_makers', sa.Column('relevance_score', sa.Integer(), nullable=True))
    op.add_column('decision_makers', sa.Column('relevance_explanation', sa.Text(), nullable=True))
    op.create_index(op.f('ix_decision_makers_relevance_score'), 'decision_makers', ['relevance_score'], unique=False)
    op.drop_column('decision_makers', 'similarity_score')
    op.add_column('target_companies', sa.Column('relevance_score', sa.Integer(), nullable=True))
    op.add_column('target_companies', sa.Column('relevance_explanation', sa.Text(), nullable=True))
    op.create_index(op.f('ix_target_companies_relevance_score'), 'target_companies', ['relevance_score'], unique=False)
    op.drop_column('target_companies', 'similarity_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_companies', sa.Column('similarity_score', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_target_companies_relevance_score'), table_name='target_companies')
    op.drop_column('target_companies', 'relevance_explanation')
    op.drop_column('target_companies', 'relevance_score')
    op.add_column('decision_makers', sa.Column('similarity_score', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_decision_makers_relevance_score'), table_name='decision_makers')
    op.drop_column('decision_makers', 'relevance_explanation')
    op.drop_column('decision_makers', 'relevance_score')
    # ### end Alembic commands ###
