"""add_refresh_token_model

Revision ID: f0a98272d0a6
Revises: a20260425_0007
Create Date: 2026-04-29 12:43:29.870554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0a98272d0a6'
down_revision: Union[str, None] = 'a20260425_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manually added to handle PostgreSQL ENUM type creation before column additions
    prospectstate_enum = postgresql.ENUM('NEW', 'DRAFTED', 'INITIAL_SENT', 'WAITING_FOR_REPLY', 'DISCOVERY_EXPIRED', 'REMINDER_1_SENT', 'REMINDER_2_SENT', 'FOLLOWUP_ACTIVE', 'POSITIVE', 'NEGATIVE', 'NEUTRAL', 'DISCOVERY_CALL', 'MEETING_BOOKED', 'ON_HOLD', 'TERMINATED', name='prospectstate')
    prospectstate_enum.create(op.get_bind(), checkfirst=True)
    
    prospectterminationreason_enum = postgresql.ENUM('NEGATIVE_REPLY', 'NO_RESPONSE', 'FOLLOWUP_EXHAUSTED', 'DISCOVERY_TIMEOUT', 'INVALID_SCHEDULE', 'INTERNAL_LEAD_SECURED', 'MANUAL', name='prospectterminationreason')
    prospectterminationreason_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('prospect_lifecycle_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('dm_id', sa.String(), nullable=False),
    sa.Column('from_state', postgresql.ENUM('NEW', 'DRAFTED', 'INITIAL_SENT', 'WAITING_FOR_REPLY', 'DISCOVERY_EXPIRED', 'REMINDER_1_SENT', 'REMINDER_2_SENT', 'FOLLOWUP_ACTIVE', 'POSITIVE', 'NEGATIVE', 'NEUTRAL', 'DISCOVERY_CALL', 'MEETING_BOOKED', 'ON_HOLD', 'TERMINATED', name='prospectstate', create_type=False), nullable=True),
    sa.Column('to_state', postgresql.ENUM('NEW', 'DRAFTED', 'INITIAL_SENT', 'WAITING_FOR_REPLY', 'DISCOVERY_EXPIRED', 'REMINDER_1_SENT', 'REMINDER_2_SENT', 'FOLLOWUP_ACTIVE', 'POSITIVE', 'NEGATIVE', 'NEUTRAL', 'DISCOVERY_CALL', 'MEETING_BOOKED', 'ON_HOLD', 'TERMINATED', name='prospectstate', create_type=False), nullable=True),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dm_id'], ['decision_makers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_lifecycle_transitions_campaign_id'), 'prospect_lifecycle_transitions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_prospect_lifecycle_transitions_created_at'), 'prospect_lifecycle_transitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prospect_lifecycle_transitions_dm_id'), 'prospect_lifecycle_transitions', ['dm_id'], unique=False)
    op.create_index(op.f('ix_prospect_lifecycle_transitions_reason'), 'prospect_lifecycle_transitions', ['reason'], unique=False)
    op.create_index(op.f('ix_prospect_lifecycle_transitions_to_state'), 'prospect_lifecycle_transitions', ['to_state'], unique=False)
    op.create_table('outbound_dispatches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('dm_id', sa.String(), nullable=False),
    sa.Column('draft_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('dispatch_key', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('dispatch_started_at', sa.DateTime(), nullable=True),
    sa.Column('dispatch_completed_at', sa.DateTime(), nullable=True),
    sa.Column('dispatch_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dm_id'], ['decision_makers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['email_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_key', name='_outbound_dispatch_key_uc')
    )
    op.create_index(op.f('ix_outbound_dispatches_action_type'), 'outbound_dispatches', ['action_type'], unique=False)
    op.create_index(op.f('ix_outbound_dispatches_campaign_id'), 'outbound_dispatches', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_outbound_dispatches_created_at'), 'outbound_dispatches', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbound_dispatches_dispatch_key'), 'outbound_dispatches', ['dispatch_key'], unique=False)
    op.create_index(op.f('ix_outbound_dispatches_dm_id'), 'outbound_dispatches', ['dm_id'], unique=False)
    op.create_index(op.f('ix_outbound_dispatches_draft_id'), 'outbound_dispatches', ['draft_id'], unique=False)
    op.create_index(op.f('ix_outbound_dispatches_state'), 'outbound_dispatches', ['state'], unique=False)
    op.add_column('campaigns', sa.Column('status_reason', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    op.add_column('campaigns', sa.Column('locked_by', sa.String(), nullable=True))
    op.create_unique_constraint('_communication_message_direction_uc', 'communication_logs', ['message_id', 'direction'])
    op.add_column('decision_makers', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('decision_makers', sa.Column('state', postgresql.ENUM('NEW', 'DRAFTED', 'INITIAL_SENT', 'WAITING_FOR_REPLY', 'DISCOVERY_EXPIRED', 'REMINDER_1_SENT', 'REMINDER_2_SENT', 'FOLLOWUP_ACTIVE', 'POSITIVE', 'NEGATIVE', 'NEUTRAL', 'DISCOVERY_CALL', 'MEETING_BOOKED', 'ON_HOLD', 'TERMINATED', name='prospectstate', create_type=False), nullable=True))
    op.add_column('decision_makers', sa.Column('termination_reason', postgresql.ENUM('NEGATIVE_REPLY', 'NO_RESPONSE', 'FOLLOWUP_EXHAUSTED', 'DISCOVERY_TIMEOUT', 'INVALID_SCHEDULE', 'INTERNAL_LEAD_SECURED', 'MANUAL', name='prospectterminationreason', create_type=False), nullable=True))
    op.add_column('decision_makers', sa.Column('last_sent_at', sa.DateTime(), nullable=True))
    op.add_column('decision_makers', sa.Column('last_reply_at', sa.DateTime(), nullable=True))
    op.add_column('decision_makers', sa.Column('next_action_at', sa.DateTime(), nullable=True))
    op.add_column('decision_makers', sa.Column('retry_after', sa.DateTime(), nullable=True))
    op.add_column('decision_makers', sa.Column('reminder_count', sa.Integer(), nullable=True))
    op.add_column('decision_makers', sa.Column('intent_last', sa.String(), nullable=True))
    op.add_column('decision_makers', sa.Column('hold_source_dm_id', sa.String(), nullable=True))
    op.add_column('decision_makers', sa.Column('held_at', sa.DateTime(), nullable=True))
    op.add_column('decision_makers', sa.Column('hold_release_at', sa.DateTime(), nullable=True))
    op.add_column('decision_makers', sa.Column('pre_hold_state', postgresql.ENUM('NEW', 'DRAFTED', 'INITIAL_SENT', 'WAITING_FOR_REPLY', 'DISCOVERY_EXPIRED', 'REMINDER_1_SENT', 'REMINDER_2_SENT', 'FOLLOWUP_ACTIVE', 'POSITIVE', 'NEGATIVE', 'NEUTRAL', 'DISCOVERY_CALL', 'MEETING_BOOKED', 'ON_HOLD', 'TERMINATED', name='prospectstate', create_type=False), nullable=True))
    op.add_column('decision_makers', sa.Column('pre_hold_status', sa.String(), nullable=True))
    op.add_column('decision_makers', sa.Column('pre_hold_next_action_at', sa.DateTime(), nullable=True))
    op.add_column('decision_makers', sa.Column('scheduled_time_utc', sa.DateTime(), nullable=True))
    op.add_column('decision_makers', sa.Column('display_timezone', sa.String(), nullable=True))
    op.add_column('decision_makers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_decision_makers_status'), table_name='decision_makers')
    op.create_unique_constraint('_campaign_dm_email_uc', 'decision_makers', ['campaign_id', 'email'])
    op.create_unique_constraint('_company_dm_name_uc', 'decision_makers', ['target_company_id', 'name'])
    op.create_index(op.f('ix_decision_makers_hold_release_at'), 'decision_makers', ['hold_release_at'], unique=False)
    op.create_index(op.f('ix_decision_makers_hold_source_dm_id'), 'decision_makers', ['hold_source_dm_id'], unique=False)
    op.create_index(op.f('ix_decision_makers_next_action_at'), 'decision_makers', ['next_action_at'], unique=False)
    op.create_index(op.f('ix_decision_makers_retry_after'), 'decision_makers', ['retry_after'], unique=False)
    op.create_index(op.f('ix_decision_makers_state'), 'decision_makers', ['state'], unique=False)
    op.create_index(op.f('ix_decision_makers_termination_reason'), 'decision_makers', ['termination_reason'], unique=False)
    op.create_index(op.f('ix_decision_makers_thread_id'), 'decision_makers', ['thread_id'], unique=False)
    op.drop_column('decision_makers', 'timezone')
    op.drop_column('decision_makers', 'scheduled_time')
    op.add_column('email_drafts', sa.Column('draft_type', sa.String(), nullable=True))
    op.add_column('email_drafts', sa.Column('dispatch_state', sa.String(), nullable=True))
    op.add_column('email_drafts', sa.Column('dispatch_started_at', sa.DateTime(), nullable=True))
    op.add_column('email_drafts', sa.Column('dispatch_completed_at', sa.DateTime(), nullable=True))
    op.add_column('email_drafts', sa.Column('dispatch_error', sa.Text(), nullable=True))
    op.create_unique_constraint('_dm_followup_uc', 'email_drafts', ['decision_maker_id', 'followup_index'])
    op.create_index(op.f('ix_email_drafts_dispatch_state'), 'email_drafts', ['dispatch_state'], unique=False)
    op.add_column('oauth_accounts', sa.Column('mailbox_health_status', sa.String(), nullable=True))
    op.add_column('oauth_accounts', sa.Column('mailbox_last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('oauth_accounts', sa.Column('mailbox_last_error', sa.Text(), nullable=True))
    op.create_unique_constraint('_user_provider_oauth_uc', 'oauth_accounts', ['user_id', 'provider'])
    op.create_index(op.f('ix_oauth_accounts_mailbox_health_status'), 'oauth_accounts', ['mailbox_health_status'], unique=False)
    op.add_column('target_companies', sa.Column('identity_key', sa.String(), nullable=True))
    op.create_unique_constraint('_campaign_domain_uc', 'target_companies', ['campaign_id', 'domain'])
    op.create_unique_constraint('_campaign_identity_uc', 'target_companies', ['campaign_id', 'identity_key'])
    op.create_index(op.f('ix_target_companies_identity_key'), 'target_companies', ['identity_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_companies_identity_key'), table_name='target_companies')
    op.drop_constraint('_campaign_identity_uc', 'target_companies', type_='unique')
    op.drop_constraint('_campaign_domain_uc', 'target_companies', type_='unique')
    op.drop_column('target_companies', 'identity_key')
    op.drop_index(op.f('ix_oauth_accounts_mailbox_health_status'), table_name='oauth_accounts')
    op.drop_constraint('_user_provider_oauth_uc', 'oauth_accounts', type_='unique')
    op.drop_column('oauth_accounts', 'mailbox_last_error')
    op.drop_column('oauth_accounts', 'mailbox_last_checked_at')
    op.drop_column('oauth_accounts', 'mailbox_health_status')
    op.drop_index(op.f('ix_email_drafts_dispatch_state'), table_name='email_drafts')
    op.drop_constraint('_dm_followup_uc', 'email_drafts', type_='unique')
    op.drop_column('email_drafts', 'dispatch_error')
    op.drop_column('email_drafts', 'dispatch_completed_at')
    op.drop_column('email_drafts', 'dispatch_started_at')
    op.drop_column('email_drafts', 'dispatch_state')
    op.drop_column('email_drafts', 'draft_type')
    op.add_column('decision_makers', sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('decision_makers', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_decision_makers_thread_id'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_termination_reason'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_state'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_retry_after'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_next_action_at'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_hold_source_dm_id'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_hold_release_at'), table_name='decision_makers')
    op.drop_constraint('_company_dm_name_uc', 'decision_makers', type_='unique')
    op.drop_constraint('_campaign_dm_email_uc', 'decision_makers', type_='unique')
    op.create_index(op.f('ix_decision_makers_status'), 'decision_makers', ['status'], unique=False)
    op.drop_column('decision_makers', 'created_at')
    op.drop_column('decision_makers', 'display_timezone')
    op.drop_column('decision_makers', 'scheduled_time_utc')
    op.drop_column('decision_makers', 'pre_hold_next_action_at')
    op.drop_column('decision_makers', 'pre_hold_status')
    op.drop_column('decision_makers', 'pre_hold_state')
    op.drop_column('decision_makers', 'hold_release_at')
    op.drop_column('decision_makers', 'held_at')
    op.drop_column('decision_makers', 'hold_source_dm_id')
    op.drop_column('decision_makers', 'intent_last')
    op.drop_column('decision_makers', 'reminder_count')
    op.drop_column('decision_makers', 'retry_after')
    op.drop_column('decision_makers', 'next_action_at')
    op.drop_column('decision_makers', 'last_reply_at')
    op.drop_column('decision_makers', 'last_sent_at')
    op.drop_column('decision_makers', 'termination_reason')
    op.drop_column('decision_makers', 'state')
    op.drop_column('decision_makers', 'is_email_verified')
    op.drop_constraint('_communication_message_direction_uc', 'communication_logs', type_='unique')
    op.drop_column('campaigns', 'locked_by')
    op.drop_column('campaigns', 'last_heartbeat')
    op.drop_column('campaigns', 'status_reason')
    op.drop_index(op.f('ix_outbound_dispatches_state'), table_name='outbound_dispatches')
    op.drop_index(op.f('ix_outbound_dispatches_draft_id'), table_name='outbound_dispatches')
    op.drop_index(op.f('ix_outbound_dispatches_dm_id'), table_name='outbound_dispatches')
    op.drop_index(op.f('ix_outbound_dispatches_dispatch_key'), table_name='outbound_dispatches')
    op.drop_index(op.f('ix_outbound_dispatches_created_at'), table_name='outbound_dispatches')
    op.drop_index(op.f('ix_outbound_dispatches_campaign_id'), table_name='outbound_dispatches')
    op.drop_index(op.f('ix_outbound_dispatches_action_type'), table_name='outbound_dispatches')
    op.drop_table('outbound_dispatches')
    op.drop_index(op.f('ix_prospect_lifecycle_transitions_to_state'), table_name='prospect_lifecycle_transitions')
    op.drop_index(op.f('ix_prospect_lifecycle_transitions_reason'), table_name='prospect_lifecycle_transitions')
    op.drop_index(op.f('ix_prospect_lifecycle_transitions_dm_id'), table_name='prospect_lifecycle_transitions')
    op.drop_index(op.f('ix_prospect_lifecycle_transitions_created_at'), table_name='prospect_lifecycle_transitions')
    op.drop_index(op.f('ix_prospect_lifecycle_transitions_campaign_id'), table_name='prospect_lifecycle_transitions')
    op.drop_table('prospect_lifecycle_transitions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
